kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-data
  labels:
    type: local
  annotations:
    volume.alpha.kubernetes.io/storage-class: rabbitmq-data
spec:
  storageClassName: rabbitmq-data
  capacity:
    storage: 15Gi
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/opt/rabbitmq-data"
